In [17]:
knitr::opts_chunk$set(warning=F,message=F,echo=T,include = T)

rm(list=ls())

library(tidyverse)
install.packages("skimr")
library(skimr)

##total for bottom row
sum_rows = function(x) {
  x = as.data.frame(x)
  sums = sapply(x,function(col) if (is.numeric(col)) sum(col, na.rm = T) else NA)
  sums = as.data.frame(t(sums))
  names(sums) = names(x)
  rbind(x, sums)
}

## right column for total
sum_cols = function(x) {
  x$Total = rowSums(x[sapply(x, is.numeric)], na.rm = T)
  x
}

desc_stats = function(x){
  x %>%
    summarise(mean = mean(x,na.rm=T),
              median = median(x,na.rm=T),
              stan_dev = sd(x,na.rm=T))
}

options(scipen=999) # disable scientific notation

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

## Import

In [18]:
data = read.csv("https://drive.google.com/uc?export=download&id=1C0WCLSx2jEsInm_NNbCgNKx6qWRNkp-Q")

names(data) = trimws(str_to_lower(str_replace_all(names(data), " ", "_")))

#sum(duplicated(data$member.id)) no duplicates

skimr::skim(data)

── Data Summary ────────────────────────
                           Values
Name                       data
Number of rows             755
Number of columns          16
_______________________
Column type frequency:
  character                9
  logical                  1
  numeric                  6
________________________
Group variables            None

── Variable type: character ────────────────────────────────────────────────────
  skim_variable         n_missing complete_rate min max empty n_unique
1 name                          0             1   1  30     0      743
2 location                      0             1   4  22     0      294
3 joined.group.on               0             1  11  18     0      428
4 last.visited.group.on         0             1  11  18     0      462
5 last.attended                 0             1   0  18   337       26
6 intro                         0             1   2   2     0        1
7 photo                         0             1   2   3     0        2
8 role                          0             1   6  12     0        3
9 url.of.member.profile         0             1  63  65     0      755
  whitespace
1          0
2          0
3          0
4          0
5          0
6          0
7          0
8          0
9          0

── Variable type: logical ──────────────────────────────────────────────────────
  skim_variable n_missing complete_rate mean count
1 title               755             0  NaN ": "

── Variable type: numeric ──────────────────────────────────────────────────────
  skim_variable        n_missing complete_rate    mean            sd      p0
1 member.id                    0             1 3.17e+8 120616120.    1043629
2 all.time.rsvps               0             1 1.00e+0         1.57        0
3 all.time..yes..rsvps         0             1 9.83e-1         1.57        0
4 all.time..no..rsvps          0             1 2.12e-2         0.153       0
5 events.attended              0             1 7.97e-1         1.39        0
6 no.shows                     0             1 0               0           0
         p25       p50       p75      p100 hist
1 252026332. 375306708 400874991 479606906 ▂▁▃▅▇
2         0          1         1        30 ▇▁▁▁▁
3         0          1         1        30 ▇▁▁▁▁
4         0          0         0         2 ▇▁▁▁▁
5         0          1         1        26 ▇▁▁▁▁
6         0          0         0         0 ▁▁▇▁▁

## 2) Explore

### 2.1) Count by location

In [19]:
data |>
  group_by(location) |>
  reframe(HEADCOUNT = n()) |>
  arrange(desc(HEADCOUNT)) |>
  head()

data1 = data |>
  mutate(LAST_ATTENDED = mdy(last.attended),
         LAST_VISITED = mdy(last.visited.group.on),
         IN_STATE = case_when(str_detect(location,", SC") ~ "YES",
                           TRUE ~ "NO"))

data2 = data1 |>
  group_by(location) |>
  reframe(RSVP_YES = sum(all.time..yes..rsvps,na.rm = T),
          EVENTS_ATTENDED = sum(events.attended,na.rm = T),
          ATTENDANCE_RATE = round(sum(EVENTS_ATTENDED / RSVP_YES,na.rm = T),2)) |>
  filter(RSVP_YES > 1 & EVENTS_ATTENDED > 1)

  location       HEADCOUNT
1 Columbia, SC   126
2 Charlotte, NC   52
3 Lexington, SC   24
4 Atlanta, GA     21
5 Charleston, SC  18
6 Greenville, SC  14

### 2.2) In-state vs out-of-state

In [20]:
data1 |>
  group_by(IN_STATE) |>
  reframe(HEADCOUNT = n()) |>
  sum_rows() |>
  mutate(PERCENT = round(HEADCOUNT/755,2))

  IN_STATE HEADCOUNT PERCENT
1 NO       435       0.58
2 YES      320       0.42
3 NA       755       1.00

### 2.3) Attendance rate by name and location

In [21]:
data2.1 = data1 |>
  group_by(name,location,IN_STATE,LAST_VISITED,photo) |>
  reframe(RSVP_YES = sum(all.time..yes..rsvps,na.rm = T),
          EVENTS_ATTENDED = sum(events.attended,na.rm = T),
          ATTENDANCE_RATE = round(sum(EVENTS_ATTENDED / RSVP_YES,na.rm = T),2)) |>
  filter(RSVP_YES > 1 & EVENTS_ATTENDED > 1) |>
  arrange(desc(ATTENDANCE_RATE)) |>
  arrange(desc(EVENTS_ATTENDED)) |>
  arrange(desc(LAST_VISITED))

data2.1

   name                    location             IN_STATE LAST_VISITED photo
1  Alan H. L.              Sumter, SC           YES      2026-03-09   Yes
2  Carnegie                Sumter, SC           YES      2026-03-08   Yes
3  Joshua Whitney          North Charleston, SC YES      2026-02-25   Yes
4  Jean Yoshii             Spartanburg, SC      YES      2025-12-30   No
5  Mark Oelkuct            Aiken, SC            YES      2025-12-29   Yes
6  Tomeka                  Greenville, SC       YES      2025-11-26   Yes
7  Brian Thomas            Myrtle Beach, SC     YES      2025-11-26   Yes
8  Bret Shroats            Lexington, KY        NO       2025-07-25   No
9  Garrett Havens          Columbia, SC         YES      2025-05-29   Yes
10 Milind Purohit          Ann Arbor, MI        NO       2025-05-06   Yes
11 Demarithé Wilson        Lexington, SC        YES      2025-04-03   Yes
12 Jim Eynon               Greenville, SC       YES      2025-04-01   Yes
13 Heather                 Florence, SC         YES      2025-01-30   Yes
14 Jake Reed               Augusta, GA          NO       2025-01-30   No
15 Sofiia Kosovan          Winter Springs, FL   NO       2025-01-25   Yes
16 Brayden Blackwell       Lexington, SC        YES      2024-11-07   No
17 Jennifer Lea Bonds      Augusta, GA          NO       2024-07-31   Yes
18 Chandramouli Pasumarthi Columbia, SC         YES      2024-06-27   No
19 Eliza                   Stow, OH             NO       2024-06-19   Yes
20 Joshua Ruiz             Myrtle Beach, SC     YES      2024-06-17   Yes
21 Eternal Love            Florence, SC         YES      2024-06-07   Yes
22 Gregory Morris          West Columbia, SC    YES      2024-06-06   Yes
23 S                       Lexington, SC        YES      2024-06-06   No
24 Jās Eckard              Spartanburg, SC      YES      2024-06-06   Yes
25 Mauricio                Lexington, SC        YES      2024-06-05   Yes
26 Yan Zhang               Park Forest, IL      NO       2024-06-04   No
27 Shamika                 San Diego, CA        NO       2024-06-04   Yes
28 Falisha Shoun           Oklahoma City, OK    NO       2024-05-29   Yes
29 aditya                  Atlanta, GA          NO       2024-05-29   Yes
30 Vincent                 Atlanta, GA          NO       2024-05-12   Yes
⋮  ⋮                       ⋮                    ⋮        ⋮            ⋮
57 Zachary Pacello         Charlotte, NC        NO       2023-11-30   No
58 Marc Nelson             Dallas, TX           NO       2023-11-26   Yes
59 Osa Emokpae             Charlotte, NC        NO       2023-11-24   No
60 Shannon King            Charlotte, NC        NO       2023-11-11   Yes
61 sammarra wigfall        Cayce, SC            YES      2023-11-10   Yes
62 Mickey Shoenberger      Columbus, GA         NO       2023-11-08   Yes
63 Chris                   Easton, PA           NO       2023-11-02   Yes
64 Atharva Dastane         College Station, TX  NO       2023-10-19   Yes
65 Creative Art Express    Denver, CO           NO       2023-10-10   Yes
66 Kenzie Mckenzie         Orlando, FL          NO       2023-09-18   Yes
67 Dharmpal Sharma         Lancaster, SC        YES      2023-09-09   Yes
68 Brayden                 Lexington, SC        YES      2023-09-03   No
69 Peter                   Irmo, SC             YES      2023-08-21   Yes
70 Brianna Burrell         McDonough, GA        NO       2023-08-21   Yes
71 Nirmal Kondreddy        Ronkonkoma, NY       NO       2023-08-21   No
72 Alejandro Silva         Lexington, SC        YES      2023-08-19   Yes
73 John                    Columbia, SC         YES      2023-08-14   Yes
74 Nishat Tabassum         Columbia, SC         YES      2023-08-07   Yes
75 Latha                   San Jose, CA         NO       2023-07-29   Yes
76 Eric Burden             Greenville, SC       YES      2023-07-27   Yes
77 Mitchell                Burlington, VT       NO       2023-04-18   Yes
78 Justin Battle           West Columbia, SC    YES      2023-04-05   No
79 Dayton                  Columbia, SC         YES      2023-02-26   Yes
80 Amelia Probst           Charlotte, NC        NO       2023-02-15   Yes
81 Antonio Dinkins         Camden, SC           YES      2023-02-09   No
82 christina               Blythewood, SC       YES      2023-01-26   Yes
83 Christopher Sujarit     Charlotte, NC        NO       2022-12-01   Yes
84 Joseph                  Johnson City, TN     NO       2022-10-12   Yes
85 Adraina Cheeks          Florence, SC         YES      2022-10-11   Yes
86 Gilbert Marlowe         Irmo, SC             YES      2022-10-03   No
   RSVP_YES EVENTS_ATTENDED ATTENDANCE_RATE
1   2        2              1.00
2   4        2              0.50
3   3        2              0.67
4   8        7              0.88
5  30       26              0.87
6   4        3              0.75
7   2        2              1.00
8   2        2              1.00
9   6        6              1.00
10  2        2              1.00
11  2        2              1.00
12  3        2              0.67
13 11       10              0.91
14  7        5              0.71
15  4        4              1.00
16  2        2              1.00
17  4        3              0.75
18  8        8              1.00
19  5        4              0.80
20  3        3              1.00
21  2        2              1.00
22  7        5              0.71
23  7        5              0.71
24  2        2              1.00
25  5        3              0.60
26  7        6              0.86
27  3        2              0.67
28  3        3              1.00
29  3        3              1.00
30  2        2              1.00
⋮  ⋮        ⋮               ⋮
57 2        2               1.00
58 3        3               1.00
59 2        2               1.00
60 2        2               1.00
61 2        2               1.00
62 2        2               1.00
63 2        2               1.00
64 2        2               1.00
65 2        2               1.00
66 3        3               1.00
67 4        3               0.75
68 2        2               1.00
69 5        4               0.80
70 2        2               1.00
71 2        2               1.00
72 2        2               1.00
73 2        2               1.00
74 3        2               0.67
75 3        2               0.67
76 7        7               1.00
77 2        2               1.00
78 2        2               1.00
79 2        2               1.00
80 2        2               1.00
81 2        2               1.00
82 2        2               1.00
83 4        4               1.00
84 2        2               1.00
85 2        2               1.00
86 2        2               1.00

### 2.4) In-state members only

In [23]:
data2.1 |>
  filter(IN_STATE == 'YES') |>
  select(-IN_STATE)

   name                    location             LAST_VISITED photo RSVP_YES
1  Alan H. L.              Sumter, SC           2026-03-09   Yes    2
2  Carnegie                Sumter, SC           2026-03-08   Yes    4
3  Joshua Whitney          North Charleston, SC 2026-02-25   Yes    3
4  Jean Yoshii             Spartanburg, SC      2025-12-30   No     8
5  Mark Oelkuct            Aiken, SC            2025-12-29   Yes   30
6  Tomeka                  Greenville, SC       2025-11-26   Yes    4
7  Brian Thomas            Myrtle Beach, SC     2025-11-26   Yes    2
8  Garrett Havens          Columbia, SC         2025-05-29   Yes    6
9  Demarithé Wilson        Lexington, SC        2025-04-03   Yes    2
10 Jim Eynon               Greenville, SC       2025-04-01   Yes    3
11 Heather                 Florence, SC         2025-01-30   Yes   11
12 Brayden Blackwell       Lexington, SC        2024-11-07   No     2
13 Chandramouli Pasumarthi Columbia, SC         2024-06-27   No     8
14 Joshua Ruiz             Myrtle Beach, SC     2024-06-17   Yes    3
15 Eternal Love            Florence, SC         2024-06-07   Yes    2
16 Gregory Morris          West Columbia, SC    2024-06-06   Yes    7
17 S                       Lexington, SC        2024-06-06   No     7
18 Jās Eckard              Spartanburg, SC      2024-06-06   Yes    2
19 Mauricio                Lexington, SC        2024-06-05   Yes    5
20 Keith                   Rock Hill, SC        2024-05-07   Yes    3
21 Rodney Greene           Charleston, SC       2024-04-04   Yes    5
22 Evan Pasok              Charleston, SC       2024-03-19   Yes    2
23 Therin Emmons           Florence, SC         2024-02-02   Yes    3
24 Reggie Bain             Columbia, SC         2024-02-01   Yes    2
25 Greg                    Aiken, SC            2024-01-24   Yes    2
26 John Robinson           Lexington, SC        2024-01-10   Yes    2
27 Frederick Gertz         Prosperity, SC       2023-12-06   Yes    9
28 sammarra wigfall        Cayce, SC            2023-11-10   Yes    2
29 Dharmpal Sharma         Lancaster, SC        2023-09-09   Yes    4
30 Brayden                 Lexington, SC        2023-09-03   No     2
31 Peter                   Irmo, SC             2023-08-21   Yes    5
32 Alejandro Silva         Lexington, SC        2023-08-19   Yes    2
33 John                    Columbia, SC         2023-08-14   Yes    2
34 Nishat Tabassum         Columbia, SC         2023-08-07   Yes    3
35 Eric Burden             Greenville, SC       2023-07-27   Yes    7
36 Justin Battle           West Columbia, SC    2023-04-05   No     2
37 Dayton                  Columbia, SC         2023-02-26   Yes    2
38 Antonio Dinkins         Camden, SC           2023-02-09   No     2
39 christina               Blythewood, SC       2023-01-26   Yes    2
40 Adraina Cheeks          Florence, SC         2022-10-11   Yes    2
41 Gilbert Marlowe         Irmo, SC             2022-10-03   No     2
   EVENTS_ATTENDED ATTENDANCE_RATE
1   2              1.00
2   2              0.50
3   2              0.67
4   7              0.88
5  26              0.87
6   3              0.75
7   2              1.00
8   6              1.00
9   2              1.00
10  2              0.67
11 10              0.91
12  2              1.00
13  8              1.00
14  3              1.00
15  2              1.00
16  5              0.71
17  5              0.71
18  2              1.00
19  3              0.60
20  3              1.00
21  4              0.80
22  2              1.00
23  3              1.00
24  2              1.00
25  2              1.00
26  2              1.00
27  9              1.00
28  2              1.00
29  3              0.75
30  2              1.00
31  4              0.80
32  2              1.00
33  2              1.00
34  2              0.67
35  7              1.00
36  2              1.00
37  2              1.00
38  2              1.00
39  2              1.00
40  2              1.00
41  2              1.00